/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment;

import anotherpackage.*;

public class App {

  // TODO
  public String answerQuestion1(){
    /*
    public class MyClass
    {
      private int value;
      public void setValue(int i){ / code / }
      // Other methods…
    }

    The method setValue assigns the value of i to the instance field value. What could you write for the implementation of setValue?

    (A) value = i; (B) this.value = i; (C) value == i;
    (D) Both (A) and (B).
     */
    return ""; // please return "A", "B", "C", or "D". Upper or lower case doesn't matter.
  }

  // TODO
  public String answerQuestion2(){
    /*
    A constructor

    (a) Must have the same name as the class it is declared within.
    (b) Is used to create objects.
    (c) May be declared private
    (d) Both (A) and (B) above
    (e) (a), (b) and (c) above.
     */
    return ""; // please return "A", "B", "C",  "D" or "E". Upper or lower case doesn't matter.
  }

  // TODO
  public String answerQuestion3(){
    /*
    public class MyClass
    {
    public MyClass(){/code/}
    // more code…
    }

    To instantiate MyClass, you would write?

    (a) MyClass mc = new MyClass();
    (b) MyClass mc = MyClass();
    (c) MyClass mc = MyClass;
    (d) MyClass mc = new MyClass;
    (e) The constructor of MyClass should be defined as, public void MyClass(){/code/}.
     */
    return ""; // please return "A", "B", "C",  "D" or "E". Upper or lower case doesn't matter.
  }


  // TODO
  public String answerQuestion4(){
    /*
    In java, objects are passed as
    (a) Copy of that object (b) Method called call by value
    (c) Memory address (d) Constructor
    (e) Default constructor.
     */
    return ""; // please return "A", "B", "C",  "D" or "E". Upper or lower case doesn't matter.
  }



  public static void main(String[] args) {
    // TODO: Make the necessary and meaningful modifications on the
    // TODO: Point, Segment and Triangle classes so the the code would run correctly,
    // TODO: use IntelliJ IDEA breakpoint to decide if those lines would run as expected.
    Point p1 = new Point(0, 4);
    Point p2 = new Point(3, 0);
    Point p3 = new Point(5, 8);
    Triangle triangle = new Triangle(p1, p2, p3);

    // TODO: Make the necessary and meaningful modifications on ClassInAnotherPackage file so that those lines would run correctly.
    ClassInAnotherPackage classInAnotherPackage1 = new ClassInAnotherPackage();
    ClassInAnotherPackage classInAnotherPackage2 = new ClassInAnotherPackage(p1);
    System.out.println(classInAnotherPackage2.p.getX());
  }
}
