/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment;

import anotherpackage.ClassInAnotherPackage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class AppTest {
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void restoreStreams() {
    System.setOut(originalOut);
  }

  @Test
  public void test1(){
    Point p1 = new Point();

    String result = "";

    result += p1.getX();
    p1.setX(10);
    p1.setY(20);
    result += p1.getX();
    result += p1.getY();

    Point p2 = new Point(5, 6);
    result += p2.getX();
    result += p2.getY();

    String correct_answer = "0102056";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test2(){
    Point p1 = new Point();
    Point p2 = new Point(1, 2);
    Point p3 = new Point(3, 4);
    Point p4 = new Point(5, 6);

    String result = "";

    Segment s = new Segment(p1, p2);

    result += s.getP1().getX();
    result += s.getP1().getY();
    result += s.getP2().getX();
    result += s.getP2().getY();
    s.setP2(p3);
    s.setP1(p4);
    result += s.getP1().getX();
    result += s.getP1().getY();
    result += s.getP2().getX();
    result += s.getP2().getY();

    String correct_answer = "00125634";
    assertEquals(result, correct_answer);
  }

  @Test
  public void test3(){
    Point p1 = new Point();
    Point p2 = new Point(1, 2);
    Point p3 = new Point(3, 4);
    Point p4 = new Point(5, 6);

    String result = "";

    ClassInAnotherPackage classInAnotherPackage1 = new ClassInAnotherPackage();
    classInAnotherPackage1.p = p2;
    ClassInAnotherPackage classInAnotherPackage2 = new ClassInAnotherPackage(p3);
    result += classInAnotherPackage2.p.getX();
    result += classInAnotherPackage1.p.getX();
    result += classInAnotherPackage2.p.getY();
    result += classInAnotherPackage1.p.getY();

    String correct_answer = "3142";
    assertEquals(result, correct_answer);
  }


  @Test
  public void test4(){
    String result = "";
    App app = new App();
    result += app.answerQuestion1();
    result += app.answerQuestion2();
    result += app.answerQuestion3();
    result += app.answerQuestion4();

    String correct_answer = "DEAC";
    assertEquals(result.toUpperCase(), correct_answer);
  }


}
